import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import type { Plugin } from "vite";

/**
 * Vite plugin that generates a version.ts file from package.json
 * This ensures the version is always in sync with package.json
 */
export function versionPlugin(): Plugin {
  return {
    name: "version-plugin",
    buildStart() {
      // Read package.json
      const packageJsonPath = join(process.cwd(), "package.json");
      const packageJson = JSON.parse(
        readFileSync(packageJsonPath, "utf-8")
      ) as { version: string; name: string };

      // Generate version.ts content
      const versionContent = `// Auto-generated from package.json - do not edit manually
// This file is generated by vite-plugin-version.ts
export const VERSION = "${packageJson.version}";
export const APP_NAME = "${packageJson.name}";
`;

      // Write version.ts to src directory
      const versionPath = join(process.cwd(), "src", "version.ts");
      writeFileSync(versionPath, versionContent, "utf-8");
    },
  };
}
