import { readFileSync, writeFileSync } from "fs";
import { join, resolve } from "path";
import type { Plugin } from "vite";

/**
 * Vite plugin that generates a version.ts file from package.json
 * This ensures the version is always in sync with package.json
 * Watches for changes in dev mode to enable HMR
 */
export function versionPlugin(): Plugin {
  const generateVersionFile = () => {
    // Read package.json
    const packageJsonPath = join(process.cwd(), "package.json");
    const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8")) as {
      version: string;
      name: string;
    };

    // Generate version.ts content
    const versionContent = `// Auto-generated from package.json - do not edit manually
// This file is generated by vite-plugin-version.ts
export const VERSION = "${packageJson.version}";
export const APP_NAME = "${packageJson.name}";
`;

    // Write version.ts to src directory
    const versionPath = resolve(process.cwd(), "src/version.ts");
    writeFileSync(versionPath, versionContent, "utf-8");
  };

  return {
    name: "version-plugin",
    buildStart() {
      generateVersionFile();
    },
    configureServer(server) {
      // Ensure package.json is watched
      const packageJsonPath = resolve(process.cwd(), "package.json");
      server.watcher.add(packageJsonPath);
    },
    handleHotUpdate({ file, server }) {
      // Watch for package.json changes
      if (file.endsWith("package.json")) {
        generateVersionFile();
        // Invalidate and update the version.ts module
        const versionModulePath = resolve(process.cwd(), "src/version.ts");
        const module = server.moduleGraph.getModuleById(versionModulePath);
        if (module) {
          server.moduleGraph.invalidateModule(module);
          // Return the module to trigger HMR
          return [module];
        }
      }
    },
  };
}
